### ISSUE TITLE
Patterns for handling reconnect/channel close

### ISSUE THREAD

**Issue by mattdsteele** [mch/python-ant#19]
Hi! I've been working on a project using python-ant; and it's been a ton of fun.

One issue I've run into is how to handle search timeouts and channel close events in a safe manner; I didn't see any examples that showed robust error handling; I'm wondering if there are patterns I should be following?

For context, I'm looking to setup a Raspberry Pi with an ANT+ sensor near a stationary bicycle with a cadence sensor. The sensor only begins broadcasting when I start pedaling.

My current approach is to define a sensor subclassing `DeviceProfile` and pass in callbacks:

```python
class CadenceRx(DeviceProfile):
    channelPeriod = 8102
    channelFrequency = 0x39
    deviceType = 0x7a # Bike Cadence Sensor

    # ... snip

    def __init__(self, node, network, callbacks=None):
        super(CadenceRx, self).__init__(node, network, callbacks)
```

```python
    # ... snip
    cadence = CadenceRx(antnode, network, 
    {'onDevicePaired': device_paired,
     'onSearchTimeout': search_timed_out,
     'onChannelClosed': channel_closed,
     'onData': data}
    )
    cadence.open()
```

If no sensors are nearby, I tend to see the `search_timed_out` callback first get invoked; and followed by `channel_closed`.

I haven't been able to re-trigger a search without incurring an error. For example:

```python
def search_timed_out(device_profile):
    # begin searching again? Doesn't seem to work :(
    cadence.open()
```

This does not seem to start a search, and I'll usually see an error in the console such as `<ChannelAssignMessage: C(1)>: timeout`

I've tried a few approaches, including trying to close and reopen `antnode`, or to run `reset_USB_Device()`; but always get an error (various examples I can provide) or the program crashes outright.

Any suggestions? My current workaround is just to kill and restart the entire Python program, but I have to imagine there's a more robust approach. Thanks!

**Comment by mch** [comment]
Hi, glad to hear you've found this useful and are having fun with it! 

I haven't worked on this repo in quite a while so I don't have many suggestions unfortunately. The one thing that comes to mind based on the message you are getting when you try call `cadence.open()` in your search timed out is that you may need to first call `cadence.close()`. 

I notice that the implementation of `DeviceProfile.close()` doesn't call `unassign()` on the channel, and that it might be necessary to unassign the channel after closing it. Not really sure though; but usually it's nice for things like that to be symmetrical, and `DeviceProfile.open()` calls `channel.assign()` before calling `channel.open()`. 

If `channel.unassign()` is not called, the channel is still attached to the network, and the `self.node.getFreeChannel()` is likely going to get a different channel which may not be possible on your device. 

Hope that helps.

**Comment by mattdsteele** [comment]
Thanks for the tips! Unfortunately I'm seeing similar errors such as`<ChannelUnassignMessage: C(1)>: timeout` errors when calling `cadence.close()` or `channel.unassign()` when run in the `search_timed_out` callback; this happens regardless of order.

I'm starting to think there might be some physical issues with my ANT+ sensor (I'm using a years-old Suunto Movestick, which has caused issues in other contexts (it periodically crashes my Windows machine when I use it in apps, for example)

I'll close this, but will keep investigating, and post in here if I notice anything new. Appreciate your help!
