### ISSUE TITLE
Bicycle Power device profile

### ISSUE THREAD

**Issue by David-Hari** [mch/python-ant#2]
Hi @mch,

I need to interface with the ANT+ power device, but you have only implemented heart-rate and ant stride. 
Are you planning on implementing the power device profile any time soon? I am going to start work on it in a fork, so perhaps we can collaborate.
I will use this issue to ask any questions I have about how your code works.

**Comment by mch** [comment]
I don't have one of those, so I'm not able to work on it much. I'd be happy to answer questions about the code. If you haven't already found it, register for an account on http://thisisant.com/ and check out the [device profile](https://www.thisisant.com/developer/ant-plus/device-profiles/#521_tab) and [specification](https://www.thisisant.com/resources/bicycle-power/).

**Comment by David-Hari** [comment]
Ok, fair enough
I have got the doc you mention, and am currently reading it. Writing code to extract the data should be easy, but I'll ask if i run into any problems.
