### ISSUE TITLE
Is this code supposed to be duplicated?

### ISSUE THREAD

**Issue by David-Hari** [mch/python-ant#3]
https://github.com/mch/python-ant/blob/229406db5fde52213c27d87b4a55d30b9690aa6b/src/ant/plus/plus.py#L116-L181

**Comment by mch** [comment]
Where is it duplicated?

**Comment by David-Hari** [comment]
Am I reading it wrong? Lines 116 to 181 are identical to 47 to 113, except for the assignment on line 52.
That seems like a mistake to me.

**Comment by mch** [comment]
Huh. Whoops, I guess I accidentally duplicated it somehow. Thanks for pointing that out.

**Comment by mch** [comment]
Fixed in PR #5
